name: matilda
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.12.3
  - numpy
  - tifffile
  - scipy
  - matplotlib
  - pyfai
  - pip
  - requests
  
  - pip:
    - h5py
